version: '3.8'
services:
    php-apache-environment:
        container_name: apache_page
        restart: always
        build:
            context: ./pagina
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - ./pagina/php:/var/www/html/
        ports:
            - 8001:80
    db:
        container_name: db
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: admin123
            MYSQL_DATABASE: noxus gym
            MYSQL_USER: kevin
            MYSQL_PASSWORD: root
        volumes:
          - ./pagina/database:/docker-entrypoint-initdb.d
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - '8080:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
            - db

